create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  nama text not null,
  kontak text not null unique,
  password text not null,
  pendamping text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  log_date date not null,
  tablet boolean,
  waktu_minum time,
  keluhan jsonb not null default '[]'::jsonb,
  makanan jsonb not null default '[]'::jsonb,
  jadwal_periksa date,
  updated_at timestamptz not null default now(),
  unique (user_id, log_date)
);

create or replace function public.set_daily_logs_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_daily_logs_updated_at on public.daily_logs;
create trigger trg_daily_logs_updated_at
before update on public.daily_logs
for each row
execute procedure public.set_daily_logs_updated_at();

alter table public.profiles enable row level security;
alter table public.daily_logs enable row level security;

drop policy if exists "allow_read_profiles" on public.profiles;
create policy "allow_read_profiles" on public.profiles for select to anon using (true);

drop policy if exists "allow_insert_profiles" on public.profiles;
create policy "allow_insert_profiles" on public.profiles for insert to anon with check (true);

drop policy if exists "allow_read_daily_logs" on public.daily_logs;
create policy "allow_read_daily_logs" on public.daily_logs for select to anon using (true);

drop policy if exists "allow_upsert_daily_logs" on public.daily_logs;
create policy "allow_upsert_daily_logs" on public.daily_logs for all to anon using (true) with check (true);
